#Springboot�����˿�
server:
  port: 8080

#ActiveMQ����
spring:
  activemq:
    broker-url: tcp://localhost:61616 #ActiveMQ������IP
    user: admin #ActiveMQ�����û���
    password: admin #ActiveMQ��������
  jms:
    #ָ�����Ӷ��л�������
    pub-sub-domain: false # false = Queue |  true = Topic

#��������ϵĶ�����
myQueueName: springboot-activemq-queue


